platform:
  - x86

environment:
  matrix:
    - GETOPT_PLATFORM: win32
      GETOPT_CONFIG: debug
    - GETOPT_PLATFORM: win32
      GETOPT_CONFIG: release
    - GETOPT_PLATFORM: winx64
      GETOPT_CONFIG: debug
    - GETOPT_PLATFORM: winx64
      GETOPT_CONFIG: release

install:
  - if [%GETOPT_PLATFORM%]==[win32] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - if [%GETOPT_PLATFORM%]==[winx64] call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if [%GETOPT_PLATFORM%]==[winx64] call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - git clone https://github.com/matricks/bam.git
  - cd bam
  - make_win64_msvc.bat
  - cd ..
  - bam\bam.exe config=%GETOPT_CONFIG%
  - local\%GETOPT_PLATFORM%\%GETOPT_CONFIG%\getopt_tests.exe

build: OFF
